---
HOME_DIR:  '/var/log/fastnetmon_attacks'
DATA_DIR:  '/var/log/fastnetmon_attacks'
SQLITE_DB: '/var/log/fastnetmon_attacks/process_attack.db'
LOG_FILE:  '/dev/stdout'
#LOG_FILE:  '/var/log/fastnetmon_attacks/debug.log'
LOG_LEVEL: DEBUG
EXABGP_PIPE: '/tmp/exabgp_flow.cmd'
EXABGP_DRYMODE: True

BLACKHOLE_COMMUNITY: '6768:6660'
BLACKHOLE_NEXTHOP: '10.66.66.66'
FLOW_COMMUNITY: '6768:9990'

FLOW_BAN_PPS: 30000
FLOW_BAN_BPS: 1000000000 #1Gbps

TCP_SYN_FLOOD_PPS: 10000
UDP_FLOOD_PPS:     80000
ICMP_FLOOD_PPS:    80000
GRE_FLOOD_PPS:     80000

NETWORKS:
    91.241.166.0/24:
        FLOW_BAN_PPS: 50000
    31.135.177.0/24:
        EXABGP_DRYMODE: False
